FROM php:7.2-apache

ENV TZ=Europe/Brussels
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update \
 && apt-get install wget \
 && apt-get clean \
 && export TERM=xterm

COPY src/docker/install_composer.sh /usr/local/bin

RUN chmod +x /usr/local/bin/install_composer.sh
RUN /usr/local/bin/install_composer.sh

# Add app code and make volume for mounting
ADD . /var/www
VOLUME [/var/www]
WORKDIR /var/www

RUN composer.phar install --no-ansi --no-interaction --no-progress --optimize-autoloader --profile --prefer-dist